/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as HatchHatchIdImport } from './routes/hatch.$hatchId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HatchHatchIdRoute = HatchHatchIdImport.update({
  id: '/hatch/$hatchId',
  path: '/hatch/$hatchId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/hatch/$hatchId': {
      id: '/hatch/$hatchId'
      path: '/hatch/$hatchId'
      fullPath: '/hatch/$hatchId'
      preLoaderRoute: typeof HatchHatchIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hatch/$hatchId': typeof HatchHatchIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hatch/$hatchId': typeof HatchHatchIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/hatch/$hatchId': typeof HatchHatchIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hatch/$hatchId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hatch/$hatchId'
  id: '__root__' | '/' | '/hatch/$hatchId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HatchHatchIdRoute: typeof HatchHatchIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HatchHatchIdRoute: HatchHatchIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/hatch/$hatchId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/hatch/$hatchId": {
      "filePath": "hatch.$hatchId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
